### PR TITLE
clean up a little

### PR DESCRIPTION
**Pull request by mauricefallon**
Hi @jiahao-0204 ,
I got that to run easily!

I've cleaned up the instructions for your package a little
* created a launch file for the rviz file
* Forked the Rviz plugin and commited the fix to CMakeLists. [link to repo](https://github.com/ori-drs/surfel_cloud_rviz_plugin)
* updated the instructions

Can we use the ori-drs version of this package as the main version and remove the current parent fork (jiahao-0204/surfel_map) ? 
This would avoid confusion

### CODE REVIEW

**Comment by jiahao-0204** [comment]
Hi @mauricefallon, yes sure!

**Comment by mauricefallon** [comment]
Can you simply delete  jiahao-0204/surfel_map  - so there is only one version of this module?

**Comment by jiahao-0204** [comment]
Yes, I was just wondering how to remove the upstream. It is done now!

**Comment by mauricefallon** [comment]
super - done!

**Pull request merged**
